<a href="https://colab.research.google.com/github/flin10/data-science-bootcamp/blob/main/data_science_camp_week2%20homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Load the iris dataset (first 4 columns are numeric)
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
                        delimiter=',', usecols=[0,1,2,3])
# 1. Define two custom numpy arrays, A and B
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
B = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Stack A and B vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 5  6  7  8  9 10 11 12 13 14]]
Horizontal Stack:
 [ 1  2  3  4  5  6  7  8  9 10  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# 2. Find common elements between A and B
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [ 5  6  7  8  9 10]


In [ ]:
# 3. Extract all numbers from A within a specific range (5 to 10)
filtered_A = A[(A >= 5) & (A <= 10)]
print("Filtered A (between 5 and 10):", filtered_A)

Filtered A (between 5 and 10): [ 5  6  7  8  9 10]


In [ ]:
# 4. Filter rows of iris_2d where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d:\n", filtered_iris)

Filtered iris_2d:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [ ]:
import pandas as pd

# Load the dataset from the given URL
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter the 'Manufacturer', 'Model' and 'Type' columns for every 20th row starting from the 1st row (index 0)
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

# Display the result
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [ ]:
import pandas as pd
# Load the dataset (assuming the extracted dataset is available in csv_data)
import io
# Assuming you have the CSV data in a variable called 'raw_csv_data'
raw_csv_data = """
# Paste your CSV data here
"""
# Now, create the StringIO object
data_io = io.StringIO(raw_csv_data)
df = pd.read_csv(data_io)
# Replace missing values in 'Min.Price' and 'Max.Price' with their respective mean values

# df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
# Display the updated dataframe
# import ace_tools as tools
# tools.display_dataframe_to_user(name="Updated Data with Missing Values Replaced", dataframe=df)

In [ ]:
import pandas as pd
import numpy as np

# Create a DataFrame with random integers
df = pd.DataFrame(np.random.randint(10, 40, (15, 4)))  # Adjusting shape to match the example

# Filter rows where the sum of values in a row is greater than 100
filtered_df = df[df.sum(axis=1) > 100]

# Display the filtered DataFrame

